name: JMeter Performance Tests

on:
  push:
    branches: [ main ]

jobs:
  performance-test:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download Apache JMeter
        run: |
          wget -q https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          mv apache-jmeter-5.6.3 jmeter

      - name: Debug Repository Structure
        run: |
          echo "ROOT:"
          ls -la

          echo "TESTS:"
          ls -la tests

      - name: Run JMeter Test
        run: |
          mkdir -p results
          mkdir -p reports

          jmeter/bin/jmeter -n \
            -t tests/load_test.jmx \
            -l results/results.csv \
            -Jjmeter.save.saveservice.output_format=csv \
            -j results/jmeter.log || true

      - name: Show JMeter Log
        run: |
          echo "===== JMETER LOG ====="

          if [ -f results/jmeter.log ]; then
            cat results/jmeter.log
          else
            echo "No log file found"
          fi

      - name: Show Results File
        run: |
          echo "===== RESULTS ====="

          if [ -f results/results.csv ]; then
            head results/results.csv
          else
            echo "No results file found"
          fi

      - name: Generate HTML Report
        run: |
          if [ -f results/results.csv ]; then
            jmeter/bin/jmeter \
              -g results/results.csv \
              -o reports || true
          else
            echo "results.csv missing"
          fi

      - name: List Reports Folder
        run: |
          echo "===== REPORTS ====="
          ls -la reports || true

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jmeter-report
          path: reports/

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jmeter-logs
          path: results/